### numpy 모듈의 호출

In [1]:
import numpy as np

#### array 생성

In [2]:
test_array = np.array(["1", "4", 5, 8], float) # data type 
test_array

array([1., 4., 5., 8.])

In [3]:
type(test_array[3])

numpy.float64

In [4]:
test_array = np.array([1, 4, 5, "8"], np.float32) # String Type의 데이터를 입력해도
test_array

array([1., 4., 5., 8.], dtype=float32)

In [6]:
type(test_array[3])   # Float Type으로 자동 형변환을 실시

numpy.float32

In [7]:
test_array.dtype   # Array(배열) 전체의 데이터 Type을 반환함

dtype('float32')

In [8]:
test_array.shape # Array(배열) 전체의 데이터 Type을 반환함

(4,)

####  array shape

In [9]:
vector  = [1,2,3,4]
np.array(vector, int).shape

(4,)

In [10]:
matrix  = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [11]:
tensor  = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(4, 3, 4)

In [12]:
np.array(tensor, int).ndim

3

In [13]:
np.array(tensor, int).size

48

#### numpy dtype

In [14]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], dtype=int)

In [15]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

In [16]:
np.array([[1, 2, 3], [4.5, "5", "6"]], 
         dtype=np.float32).nbytes

24

In [17]:
np.array([[1, 2, 3], [4.5, "5", "6"]], 
         dtype=np.int8).nbytes

6

In [19]:
np.array([[1, 2, 3], [4.5, "5", "6"]], 
         dtype=np.float64).nbytes


48

### shape handling

In [20]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [21]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [22]:
test =np.array(test_matrix).reshape(8,)
test

array([1, 2, 3, 4, 1, 2, 5, 8])

In [23]:
test.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [1],
       [2],
       [5],
       [8]])

In [24]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [25]:
np.array(test_matrix).reshape(2,-1).shape

(2, 4)

In [26]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [27]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

### flat or flatten()

In [28]:
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

## indexing & slicing

In [29]:
test_exmaple = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_exmaple

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
test_exmaple[0][0]

1

In [32]:
test_exmaple[0,0]

1

In [33]:
test_exmaple[0,0] = 10 # Matrix 0,0 에 12 할당
test_exmaple

array([[10,  2,  3],
       [ 4,  5,  6]])

In [34]:
test_exmaple[0][0] = 5 # Matrix 0,0 에 12 할당
test_exmaple[0,0]

5

### slicing

In [35]:
test_exmaple = np.array([
    [1, 2, 5,8], [1, 2, 5,8],[1, 2, 5,8],[1, 2, 5,8]], int)
test_exmaple[:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [36]:
test_exmaple[:,1:3] 
test_exmaple[1,:2] 

array([1, 2])

In [37]:
test_exmaple = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
test_exmaple[:,2:] # 전체 Row의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [38]:
test_exmaple[1,1:3] # 1 Row의 1열 ~ 2열

array([7, 8])

In [39]:
test_exmaple[1:3] # 1 Row ~ 2Row의 전체

array([[ 6,  7,  8,  9, 10]])

In [40]:
a = np.arange(100).reshape(10,10)
a[:, -1].reshape(-1,1)

array([[ 9],
       [19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])

## creation function

In [41]:
np.arange(30).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [60]:
np.arange(0, 5, 0.5).tolist()

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]

In [43]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

ones, zeros & empty 

In [44]:
np.zeros(shape=(10,), dtype=np.int8) # 10 - zero vector 생성

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [45]:
np.zeros((2,5)) # 2 by 5 - zero matrix 생성

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [47]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
np.empty(shape=(10,), dtype=np.int8) 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [49]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
test_matrix = np.arange(30).reshape(5,6)
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

### eye, identity & digonal

In [51]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [52]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [54]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [57]:
np.diag(matrix, k=1)

array([1, 5])

In [58]:
np.random.uniform(0,1,10).reshape(2,5)

array([[0.91206759, 0.26909682, 0.80375771, 0.89656386, 0.54975827],
       [0.37147855, 0.37242442, 0.56262571, 0.37976081, 0.7069065 ]])

In [59]:
np.random.normal(0,1,10).reshape(2,5)

array([[ 1.98372179, -1.28034322, -0.82962384,  0.55282497, -1.58797723],
       [ 0.99353282,  0.04091503, -0.56688147,  1.69352627, -0.7779423 ]])

### operation in array

In [61]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
test_array.sum(dtype=np.float)

C:\Users\aaaaader567\AppData\Local\Temp\ipykernel_16788\3740136754.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_array.sum(dtype=np.float)


55.0

In [63]:
test_array = np.arange(1,13).reshape(3,4)
test_array.sum()

78

In [64]:
test_array.sum(axis=1)

array([10, 26, 42])

In [65]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [66]:
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [67]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [68]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [69]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [71]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
test_array.mean(), test_array.mean(axis=0)

(6.5, array([5., 6., 7., 8.]))

In [73]:
test_array.std(), test_array.std(axis=0)

(3.452052529534663, array([3.26598632, 3.26598632, 3.26598632, 3.26598632]))

In [74]:
np.exp(test_array), np.sqrt(test_array)

(array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
        [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
        [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]),
 array([[1.        , 1.41421356, 1.73205081, 2.        ],
        [2.23606798, 2.44948974, 2.64575131, 2.82842712],
        [3.        , 3.16227766, 3.31662479, 3.46410162]]))

### concatenate

In [75]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [76]:
a = np.array([ [1], [2], [3]])
b = np.array([ [2], [3], [4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [77]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
np.concatenate( (a,b) ,axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [78]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np.concatenate( (a,b.T) ,axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [79]:
a.tolist()

[[1, 2], [3, 4]]

### all & any

In [80]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [82]:
np.any(a>5), np.any(a<0)

(True, False)

In [83]:
np.all(a>5) , np.all(a < 10)

(False, True)

### comparision operation

In [84]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b 

array([False,  True, False])

In [85]:
test_a == test_b 

array([False, False, False])

In [86]:
(test_a > test_b).any()

True

In [87]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3) # and 조건의 condition

array([ True, False, False])

In [88]:
b = np.array([True, False, True], bool)
np.logical_not(b) # NOT 조건의 condition

array([False,  True, False])

In [89]:
c = np.array([False, True, False], bool)
np.logical_or(b, c) # OR 조건의 condition

array([ True,  True,  True])

In [90]:
a

array([1., 3., 0.])

In [91]:
np.where(a > 0, 3, 2) 

array([3, 3, 2])

In [92]:
np.where(a>0)

(array([0, 1], dtype=int64),)

In [93]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [94]:
np.where(a>10)

(array([6, 7, 8, 9], dtype=int64),)

In [95]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [96]:
np.isfinite(a)

array([ True, False, False])

### argmax & argmin

In [97]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a) , np.argmin(a)

(5, 0)

In [98]:
a=np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1) , np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

### boolean index

In [99]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [100]:
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [101]:
condition = test_array < 3 
test_array[condition]

array([1., 0., 2.])

In [102]:
A = np.array([
[12, 13, 14, 12, 16, 14, 11, 10,  9],
[11, 14, 12, 15, 15, 16, 10, 12, 11],
[10, 12, 12, 15, 14, 16, 10, 12, 12],
[ 9, 11, 16, 15, 14, 16, 15, 12, 10],
[12, 11, 16, 14, 10, 12, 16, 12, 13],
[10, 15, 16, 14, 14, 14, 16, 15, 12],
[13, 17, 14, 10, 14, 11, 14, 15, 10],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 17, 19, 16, 17, 18, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 12, 14, 11, 12, 14, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11]])
B = A < 15
B.astype(np.int)

C:\Users\aaaaader567\AppData\Local\Temp\ipykernel_16788\1641836540.py:18: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  B.astype(np.int)


array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1]])

### fancy index

In [105]:
a = np.array([2, 4, 6, 8], float)

In [104]:
a[a>4] 

array([6., 8.])

In [106]:
a.take(b) #take 함수: bracket index와 같은 효과

array([4., 2., 4.])

In [107]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c] # b를 row index, c를 column index로 변환하여 표시함

array([ 1.,  4., 16., 16.,  4.])

In [108]:
a = np.array([[1, 4], [9, 16]], float)
a[b]

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 9., 16.],
       [ 9., 16.],
       [ 1.,  4.]])

### load txt

In [114]:
a = np.loadtxt("./populations.txt")
a[:10]

OSError: ./populations.txt not found.

In [110]:
a_int = a.astype(int)
a_int[:3]

array([[ 1,  4],
       [ 9, 16]])

In [111]:
np.savetxt('int_data.csv',a_int, delimiter=",")

In [112]:
np.save("npy_test", arr=a_int)

In [113]:
npy_array = np.load(file="npy_test.npy")
npy_array[:3]

array([[ 1,  4],
       [ 9, 16]])